[project]
name = "fastrtc-kroko"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastrtc[vad, stt]",
    "librosa",
    "numpy>=2.0.2",
    "sherpa-onnx",
    "click",
    "torch"
]
